### ISSUE TITLE
Thumbnail loading problem

### ISSUE THREAD

**Issue by ghost** [miku-nyan/Overchan-Android#4]
https://8ch.net/tech/
The thumbnail of the sticky (rms picture) doesn't seem to load:
![screenshot](https://a.pomf.se/pwlrpr.png)

**Comment by miku-nyan** [comment]
https://github.com/miku-nyan/Overchan-Android/commit/11c809567ecbd526499564ad854b8682b861843d

**Comment by miku-nyan** [comment]
JSON API on 8chan doesn't provide information about the extension (image format) of thumbnail files, so I assumed that it is always ".jpg".
Now it should work correctly also with "png" thumbnails.

**Comment by ctrlcctrlv** [comment]
Sorry about that. It's always JPG for new posts but posts made before a certain date matched their format.

If you need help with 8chan API, please feel free to contact me. We have an `extra_files` attribute since posts can have multiple files, you might want to add that.

If you have suggestions for a post API, please let me know them too. I can also help you query 8chan-captcha and get replies, et cetera.

Also note our API is changing as part of a rewrite of our entire infrastructure. (it will still be 4chan-compatible, but post API will change as part of https://github.com/infinity-next/infinity-next)

Exodus dev was quite unresponsive to my advice/help so I gave up on him. Hopefully it will be easier to work with you! :3

**Comment by miku-nyan** [comment]
Thank you.
Multiple attachments, `extra_files` are already supported.
Captcha is supported (detects the link to `dnsbls_bypass.php` in posting error and handles it).
If there is any features for 8chan which is not yet implemented in client, please let me know (and when API will change).
